# Generated by Django 3.2 on 2021-06-14 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('original_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Valor original')),
                ('type_item', models.CharField(choices=[('Receita', 'Receita'), ('Despesa', 'Despesa')], max_length=50, verbose_name='Tipo')),
                ('date', models.DateField(verbose_name='Data')),
                ('status_payment', models.BooleanField(default=True, verbose_name='Pago')),
                ('date_payment', models.DateField(blank=True, verbose_name='Data Vencimento')),
                ('fees', models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='Juros')),
                ('status', models.BooleanField(default=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mercurium.category')),
            ],
        ),
    ]
