# Generated by Django 3.2 on 2021-07-02 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mercurium', '0002_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mercurium.category', verbose_name='Nome categoria'),
        ),
    ]
