# Generated by Django 3.2 on 2021-07-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mercurium', '0002_alter_wallet_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Limite'),
        ),
    ]
